-- 1. Monthly Recurring Revenue (MRR)
SELECT
    payment_month,
    SUM(amount) AS monthly_recurring_revenue
FROM fact_payments
WHERE payment_status = 'Paid'
GROUP BY payment_month
ORDER BY payment_month;

--This query calculates the total successful subscription revenue collected each month.
--It excludes failed or refunded payments so that only realized recurring revenue contributes to MRR.


--2. Annual Recurring Revenue (ARR)
SELECT
    payment_month,
    SUM(amount) AS mrr,
    SUM(amount) * 12 AS arr
FROM fact_payments
WHERE payment_status = 'Paid'
GROUP BY payment_month
ORDER BY payment_month;

--ARR is typically derived as MRR × 12 for subscription businesses.


--3. Monthly Revenue Summary
SELECT
    payment_month,
    COUNT(*) AS successful_transactions,
    SUM(amount) AS revenue,
    AVG(amount) AS avg_transaction_value
FROM fact_payments
WHERE payment_status = 'Paid'
GROUP BY payment_month
ORDER BY payment_month;

--Observe overall revenue movement month over month.
--Finance teams use this to identify seasonality and unusual revenue changes.


-- 4. Revenue by Plan
SELECT
    dp.plan_name,
    dp.billing_cycle,
    SUM(fp.amount) AS total_revenue,
    COUNT(fp.payment_id) AS total_payments
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_plans AS dp
    ON fs.plan_id = dp.plan_id
WHERE fp.payment_status = 'Paid'
GROUP BY
    dp.plan_name,
    dp.billing_cycle
ORDER BY total_revenue DESC;

--Determine which subscription plans generate the most revenue.
--Helps pricing and product teams understand plan performance.


--5. Revenue by Country
SELECT
    du.country,
    SUM(fp.amount) AS total_revenue,
    COUNT(DISTINCT du.user_id) AS total_customers
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_users AS du
    ON fs.user_id = du.user_id
WHERE fp.payment_status = 'Paid'
GROUP BY du.country
ORDER BY total_revenue DESC;

--Identify highest-revenue markets.
--Supports regional investment and expansion decisions.


--6. Revenue by Acquisition Channel
SELECT
    du.acquisition_channel,
    SUM(fp.amount) AS total_revenue,
    COUNT(DISTINCT du.user_id) AS total_customers,
    AVG(fp.amount) AS avg_payment
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_users AS du
    ON fs.user_id = du.user_id
WHERE fp.payment_status = 'Paid'
GROUP BY du.acquisition_channel
ORDER BY total_revenue DESC;

--Evaluate which marketing channels generate the most revenue.
--Measures not just customer acquisition volume but the revenue quality of each acquisition source.


-- 7. Active Customers
SELECT
    COUNT(DISTINCT user_id) AS active_customers
FROM fact_subscriptions
WHERE subscription_status = 'Active';

-- Measures the current paying customer base.
-- Uses COUNT(DISTINCT) to avoid double-counting customers.


-- 8. Churn Rate
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN subscription_status = 'Cancelled' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS churn_rate_pct
FROM fact_subscriptions;

-- Measures the percentage of customers who have churned.
-- Uses conditional aggregation to calculate the churn percentage.


-- 9. Customer Retention Rate
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN subscription_status = 'Active' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS retention_rate_pct
FROM fact_subscriptions;

-- Measures the percentage of customers that remain active.
-- Complements churn rate and is commonly tracked by SaaS companies.


-- 10. Average Revenue Per User (ARPU)
SELECT
    ROUND(
        SUM(fp.amount) / COUNT(DISTINCT fs.user_id),
        2
    ) AS arpu
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
WHERE fp.payment_status = 'Paid';

-- Measures the average revenue generated per customer.
-- Calculates revenue using successful payments and unique customers.

-- 11. Customer Lifetime Value (LTV)
SELECT
    ROUND(
        (SUM(fp.amount) / COUNT(DISTINCT fs.user_id))
        *
        (AVG(fs.subscription_length_days) / 30.0),
        2
    ) AS estimated_ltv
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
WHERE fp.payment_status = 'Paid';

-- Estimates the lifetime revenue generated by an average customer.
-- Uses a simplified LTV formula suitable for portfolio projects.


-- 12. Refund Rate
SELECT
    ROUND(
        COUNT(CASE WHEN refund_flag = 1 THEN 1 END) * 100.0
        / COUNT(*),
        2
    ) AS refund_rate_pct
FROM fact_payments;

-- Measures the percentage of payments that resulted in refunds.
-- Uses conditional aggregation to identify refunded transactions.


-- 13. Monthly Revenue Trend
WITH monthly_revenue AS
(
    SELECT
        payment_month,
        SUM(amount) AS revenue
    FROM fact_payments
    WHERE payment_status = 'Paid'
    GROUP BY payment_month
)

SELECT
    payment_month,
    revenue,
    LAG(revenue) OVER (ORDER BY payment_month) AS previous_month_revenue,
    revenue - LAG(revenue) OVER (ORDER BY payment_month) AS revenue_change
FROM monthly_revenue
ORDER BY payment_month;

-- Compares each month's revenue with the previous month.
-- Uses LAG() to perform month-over-month analysis without self-joins.


-- 14. Monthly Revenue Growth Percentage
WITH monthly_revenue AS
(
    SELECT
        payment_month,
        SUM(amount) AS revenue
    FROM fact_payments
    WHERE payment_status = 'Paid'
    GROUP BY payment_month
)

SELECT
    payment_month,
    revenue,
    ROUND(
        (
            (revenue - LAG(revenue) OVER (ORDER BY payment_month))
            * 100.0
        )
        /
        NULLIF(LAG(revenue) OVER (ORDER BY payment_month), 0),
        2
    ) AS revenue_growth_pct
FROM monthly_revenue
ORDER BY payment_month;

-- Measures month-over-month revenue growth.
-- Uses NULLIF() to safely avoid division-by-zero errors.


-- 15. Plan Performance
SELECT
    dp.plan_name,
    dp.billing_cycle,
    COUNT(DISTINCT fs.user_id) AS customers,
    SUM(fp.amount) AS revenue,
    AVG(fp.amount) AS avg_payment
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_plans AS dp
    ON fs.plan_id = dp.plan_id
WHERE fp.payment_status = 'Paid'
GROUP BY
    dp.plan_name,
    dp.billing_cycle
ORDER BY revenue DESC;

-- Compares customer adoption and revenue across subscription plans.
-- Combines customer counts, revenue, and payment averages in one analysis.


-- 16. Industry Performance
SELECT
    du.industry,
    COUNT(DISTINCT fs.user_id) AS customers,
    SUM(fp.amount) AS revenue,
    AVG(fp.amount) AS avg_payment
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_users AS du
    ON fs.user_id = du.user_id
WHERE fp.payment_status = 'Paid'
GROUP BY du.industry
ORDER BY revenue DESC;

-- Compares customer value across industries.
-- Helps identify the highest-performing market segments.


-- 17. Top 10 Customers
WITH customer_revenue AS
(
    SELECT
        du.customer_id,
        du.country,
        SUM(fp.amount) AS total_revenue
    FROM fact_payments AS fp
    JOIN fact_subscriptions AS fs
        ON fp.subscription_id = fs.subscription_id
    JOIN dim_users AS du
        ON fs.user_id = du.user_id
    WHERE fp.payment_status = 'Paid'
    GROUP BY
        du.customer_id,
        du.country
)

SELECT TOP (10)
    *,
    ROW_NUMBER() OVER (ORDER BY total_revenue DESC) AS row_num
FROM customer_revenue
ORDER BY row_num;

-- Returns the ten highest-revenue customers.
-- Uses ROW_NUMBER() to assign a unique position to every customer.


-- 18. Customer Ranking Comparison
WITH customer_revenue AS
(
    SELECT
        du.customer_id,
        du.country,
        SUM(fp.amount) AS total_revenue
    FROM fact_payments AS fp
    JOIN fact_subscriptions AS fs
        ON fp.subscription_id = fs.subscription_id
    JOIN dim_users AS du
        ON fs.user_id = du.user_id
    WHERE fp.payment_status = 'Paid'
    GROUP BY
        du.customer_id,
        du.country
)

SELECT
    customer_id,
    country,
    total_revenue,

    ROW_NUMBER() OVER (
        ORDER BY total_revenue DESC
    ) AS row_number,

    RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS rank_number,

    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS dense_rank
FROM customer_revenue
ORDER BY total_revenue DESC;

-- Compares the behavior of ROW_NUMBER(), RANK(), and DENSE_RANK().
-- Demonstrates how SQL handles ranking when multiple rows have the same value.

-- 19. Monthly Cohort Retention Analysis
WITH cohort AS
(
    SELECT
        user_id,
        DATEFROMPARTS(signup_year, signup_month, 1) AS cohort_month
    FROM dim_users
),

cohort_size AS
(
    SELECT
        cohort_month,
        COUNT(*) AS cohort_size
    FROM cohort
    GROUP BY cohort_month
),

customer_activity AS
(
    SELECT DISTINCT
        fs.user_id,
        c.cohort_month,
        DATEFROMPARTS(
            YEAR(fp.payment_date),
            MONTH(fp.payment_date),
            1
        ) AS activity_month
    FROM fact_payments AS fp
    JOIN fact_subscriptions AS fs
        ON fp.subscription_id = fs.subscription_id
    JOIN cohort AS c
        ON fs.user_id = c.user_id
    WHERE fp.payment_status = 'Paid'
),

retention AS
(
    SELECT
        cohort_month,
        activity_month,
        COUNT(DISTINCT user_id) AS active_customers
    FROM customer_activity
    GROUP BY
        cohort_month,
        activity_month
)

SELECT
    r.cohort_month,
    r.activity_month,
    cs.cohort_size,
    r.active_customers,
    ROUND(
        100.0 * r.active_customers / cs.cohort_size,
        2
    ) AS retention_pct
FROM retention AS r
JOIN cohort_size AS cs
    ON r.cohort_month = cs.cohort_month
ORDER BY
    r.cohort_month,
    r.activity_month;

-- Shows how well each signup cohort is retained over time.
-- Demonstrates CTEs, date manipulation, and multi-stage analytical SQL.


-- 20. Monthly Revenue Metrics View
GO

CREATE OR ALTER VIEW vw_monthly_revenue AS
SELECT
    fp.payment_month,
    SUM(fp.amount) AS monthly_revenue,
    COUNT(fp.payment_id) AS total_payments,
    COUNT(DISTINCT fs.user_id) AS active_customers,
    ROUND(SUM(fp.amount) / COUNT(DISTINCT fs.user_id), 2) AS arpu
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
WHERE fp.payment_status = 'Paid'
GROUP BY fp.payment_month;
GO

-- Provides monthly KPIs for executive revenue reporting.
-- Creates a reusable semantic layer for Tableau dashboards.


-- 21. Plan Performance View
CREATE OR ALTER VIEW vw_plan_performance AS
SELECT
    dp.plan_name,
    dp.billing_cycle,
    COUNT(DISTINCT fs.user_id) AS customers,
    SUM(fp.amount) AS revenue,
    AVG(fp.amount) AS average_payment
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_plans AS dp
    ON fs.plan_id = dp.plan_id
WHERE fp.payment_status = 'Paid'
GROUP BY
    dp.plan_name,
    dp.billing_cycle;
GO

-- Summarizes customer adoption and revenue by subscription plan.
-- Eliminates repeated aggregation logic across dashboards.


-- 22. Customer Segmentation View
CREATE OR ALTER VIEW vw_customer_segmentation AS
SELECT
    du.customer_id,
    du.country,
    du.industry,
    du.company_size,
    du.acquisition_channel,
    SUM(fp.amount) AS lifetime_revenue,
    COUNT(fp.payment_id) AS successful_payments,
    AVG(fp.amount) AS average_payment
FROM fact_payments AS fp
JOIN fact_subscriptions AS fs
    ON fp.subscription_id = fs.subscription_id
JOIN dim_users AS du
    ON fs.user_id = du.user_id
WHERE fp.payment_status = 'Paid'
GROUP BY
    du.customer_id,
    du.country,
    du.industry,
    du.company_size,
    du.acquisition_channel;
GO

-- Creates a business-ready customer dataset for segmentation analysis.
-- Simplifies Tableau by exposing customer-level metrics in one view.

SELECT TOP (10) * FROM vw_monthly_revenue;
GO

SELECT TOP (10) * FROM vw_plan_performance;
GO

SELECT TOP (10) * FROM vw_customer_segmentation;
GO